### PR TITLE
Update waveprefixproduct.md

### PR DESCRIPTION
**Pull request by BitMD**
Fixing example code and adding a note about what is return for the first active lane.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@BitMD : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@BitMD : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@BitMD : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@BitMD : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by PRMerger6** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
