### PR TITLE
Update windows-certification-portal.md to indicate Win32 desktop app certification is deprecated

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@icnocop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@icnocop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by QuinnRadich — APPROVED** [review]

**Comment by PRMerger12** [comment]
@QuinnRadich : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by QuinnRadich** [comment]
#sign-off

**Pull request merged**
