### PR TITLE
Code update

### PR DESCRIPTION
**Pull request by jjhenry21**
Updated the code under // Display some of the contents of the chain.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@jjhenry21 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GrantMeStrength** [comment]
Joe - are you MSFT?

**Comment by jjhenry21** [comment]
I'm a contractor at Microsoft, not a direct hire.

**Comment by jjhenry21** [comment]
@GrantMeStrength   Can we merge this? thanks

**Pull request merged**
