### PR TITLE
Update memory-limits-for-windows-releases.md

### PR DESCRIPTION
**Pull request by 0xbadfca11**
Delete Windows 11 x86

### CODE REVIEW

**Comment by PRMerger9** [comment]
@0xbadfca11 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alvinashcraft** [comment]
Hi. Thanks for your contribution. The Windows 11 [download page](https://www.microsoft.com/software-download/windows11) states: "Windows 11 can only run on 64-bit CPUs.", and there are no x86 ISOs in the downloads.

**Review by alvinashcraft — APPROVED** [review]
Thanks for removing this x86 information for Windows 11.

**Comment by alvinashcraft** [comment]
#sign-off

**Pull request merged**
