### PR TITLE
Update about-windows-filtering-platform.md

### PR DESCRIPTION
**Pull request by xiaoyinl**
Remove redundant and confusing header, since this isn't a table. Also, make the component name bold.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Yes, it's possible that was a table before the migration from MSDN. I've tweaked it a bit to use markdown headings. Thanks!

**Comment by stevewhims** [comment]
Safe for you to delete your working branch now.

**Pull request merged**
