### PR TITLE
Fix SVG table link

### PR DESCRIPTION
**Pull request by wieslawsoltes**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@wieslawsoltes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@wieslawsoltes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
