### PR TITLE
Update toc.yml

### PR DESCRIPTION
**Pull request by Justinha**
Making ToC title match topic H1.

### CODE REVIEW

**Comment by Justinha** [comment]
@GrantMeStrength  fyi. please let me know if ToC and topic H1 mismatch is intentional.

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@Justinha: I'm sorry - only the author of this article, @GrantMeStrength, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by GrantMeStrength** [comment]
Merged.

**Pull request merged**
