### PR TITLE
Update using-messages-and-message-queues.md

### PR DESCRIPTION
**Pull request by DJm00n**
add syntax highlighting

### CODE REVIEW

**Comment by PRMerger12** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by hickeys — APPROVED** [review]

**Comment by hickeys** [comment]
#sign-off

**Comment by DJm00n** [comment]
@hickeys is it already merged?

**Review by tim-weis — APPROVED** [review]
Changes look good to me. Is the merge blocked on other changes, or was there a technical issue?

**Comment by hickeys** [comment]
#sign-off

**Pull request merged**
