### PR TITLE
Update memory-limits-for-windows-releases.md

### PR DESCRIPTION
**Pull request by YuriProMonkey**
New update

### CODE REVIEW

**Comment by PRMerger7** [comment]
@YuriProMonkey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by YuriProMonkey — COMMENTED** [review]
New update

**Comment by YuriProMonkey** [comment]
How can I save the edited file?

**Comment by PRMerger12** [comment]
@YuriProMonkey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alvinashcraft** [comment]
Hi. Did you intend to delete the file in this PR?

**Comment by alvinashcraft** [comment]
Hi @YuriProMonkey. Your two PRs you created to try and submit a change only contain a deleted file. If you're having trouble submitting a PR, you can try to suggest your changes in an issue instead. I will watch for new issues or PRs submitted for this topic. I am closing this PR, but you can continue to comment, and I will monitor the replies.

**Comment by YuriProMonkey** [comment]
Alvin

Thanks, but trying to add new stuff on this website like Windows server
2016.2019 and 2022.

That is ok no need to message me.

Thanks,

Yuri

**Pull request closed without merging**
