### PR TITLE
Mention UpdateProcThreadAttribute & SetHandleInformation

### PR DESCRIPTION
**Pull request by henke37**
Detailed handle inheritance control functions

### CODE REVIEW

**Comment by PRMerger9** [comment]
@henke37 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
