### PR TITLE
Small fix-ups

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@gewarren : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gewarren** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@gewarren: I'm sorry - only the author of this article, @mikben, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MatchaMatch** [comment]
Thanks for your contribution! I've merged your changes and they should be live soon.

**Pull request merged**
