### PR TITLE
Adding EAP-AKA sample

### PR DESCRIPTION
**Pull request by AllanOk**
Adds a sample WLAN profile and links to it from the main wireless profiles page

### CODE REVIEW

**Comment by PRMerger3** [comment]
@AllanOk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Thank you!

**Comment by PRMerger9** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
