### PR TITLE
Update manifest-file-schema.md

### PR DESCRIPTION
**Pull request by DJm00n**
Info on "gdiScaling" from https://docs.microsoft.com/windows/win32/sbscs/application-manifests#gdiscaling
Info on "activeCodePage" from https://docs.microsoft.com/windows/uwp/design/globalizing/use-utf8-code-page
Info on "heapType" from https://docs.microsoft.com/windows/win32/sbscs/application-manifests#heaptype

### CODE REVIEW

**Comment by PRMerger14** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
Any objections?

**Comment by mcleanbyron** [comment]
Thanks for your submission! This looks great.

**Pull request merged**
