### PR TITLE
XAudio 2.9 Redistributable docs

### PR DESCRIPTION
**Pull request by aklemets**
Added an article about the new XAudio 2.9 Redistributable NuGet package. 
Please review now, but let's not merge the changes just yet as the NuGet package has not yet been published.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@aklemets : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@aklemets : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@aklemets : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aklemets** [comment]
@drewbatgit I have published the package on nuget.org. So, we need to publish the documentation now... Would you please review this article and suggest any changes that may be necessary?

**Review by drewbatgit — APPROVED** [review]
I added the new redistributable guide article to the TOC as a child of the XAudio2 Versions page.

**Pull request merged**
