### PR TITLE
Update wm-keydown.md

### PR DESCRIPTION
**Pull request by DJm00n**
Add link to Keystroke Message Flags

### CODE REVIEW

**Comment by PRMerger10** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger17** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
