### PR TITLE
Update naming-a-file.md

### PR DESCRIPTION
**Pull request by colejohnson66**
Cleanup triplicate entries for `COM` and `LPT`.

### CODE REVIEW

**Comment by alvinashcraft** [comment]
These superscript entries were intentionally created last October with the following comment:

"Windows recognizes the 8-bit ISO/IEC 8859-1 superscript digits ¹, ², and ³ as digits and treats them as valid parts of COM# and LPT# device names, making them reserved in every directory. As far as I can tell, this is the case on all NT versions."

**Comment by colejohnson66** [comment]
Ah. Those looked like they were superscripts for missing footnotes. Perhaps this "weird" behavior could be clarified?

**Comment by alvinashcraft** [comment]
Sorry, about that @colejohnson66. It looks like my commit changed enough lines to trigger the license agreement bot. You can either follow the instructions to agree, or I can close this PR and create another PR from my own branch to get the changes merged.

**Comment by colejohnson66** [comment]
Honestly, since you basically undid my (misguided) change, I'd rather you make a new PR.

**Comment by alvinashcraft** [comment]
Will do. Thanks for bringing this to my attention. I'll get the changes merged shortly.

**Pull request closed without merging**
