### PR TITLE
Update task-maintenence.md

### PR DESCRIPTION
**Pull request by reputhot**
These changes are to clarify behavior of automatic maintenance.
Some statements that do no hold true anymore have been updated.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@reputhot : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@reputhot : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Thank you!

**Comment by PRMerger18** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
