### PR TITLE
CoreAudio: list audio endpoint properties in one place

### PR DESCRIPTION
**Pull request by DJm00n**
Clarify what is endpoint device instanceid and containerid.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@drewbatgit any comments on this?

**Comment by drewbatgit** [comment]
Sorry for the delay. I am waiting for a subject matter expert to review your changes.

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
