### PR TITLE
Should be a share path

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
Followup for
https://github.com/MicrosoftDocs/win32/pull/338

@Karl-Bridge-Microsoft

### CODE REVIEW

**Comment by PRMerger18** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by justanotheranonymoususer** [comment]
@Karl-Bridge-Microsoft you ruined it again :( `\\symbols` is a share path, it should start with two backslashes.

**Comment by PRMerger17** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
