### PR TITLE
Added description for /f option

### PR DESCRIPTION
**Pull request by miki-bgd**
Copied missing part of description for /f option, from symstore CLI-help.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@miki-bgd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
