### PR TITLE
Updates to the MRM APIs

### PR DESCRIPTION
**Pull request by ptorr-msft**
Added extensive info and corrected some errors with the MRM documentation.

### CODE REVIEW

**Comment by ptorr-msft** [comment]
@microsoft-github-policy-service agree

**Comment by ptorr-msft** [comment]
FYI I added three new files (mrmfiles, mrmresourcenames, and mrmqualifiers) and not sure what to do about the asset IDs etc.

**Comment by ptorr-msft** [comment]
@axelandrejs FYI.

**Comment by jwmsft** [comment]
> FYI I added three new files (mrmfiles, mrmresourcenames, and mrmqualifiers) and not sure what to do about the asset IDs etc.

Asset IDs are legacy metadata and not needed on new docs. I think these will be fine.

**Review by jwmsft — APPROVED** [review]

**Pull request merged**
