### PR TITLE
SSPI: Correct function signature for AcceptSecurityContext (Kerberos)

### PR DESCRIPTION
**Pull request by ThatWileyGuy**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ThatWileyGuy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ThatWileyGuy** [comment]
It looks like Digest has a similar issue: https://docs.microsoft.com/en-us/windows/win32/secauthn/acceptsecuritycontext--digest

And the General page has a syntax block with just a close-paren: https://docs.microsoft.com/en-us/windows/win32/secauthn/acceptsecuritycontext--general

**Comment by PRMerger14** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
