### PR TITLE
Add a new architecture named LoongArch

### PR DESCRIPTION
**Pull request by kilaterlee**
Add LoongArch 32-bit and LoongArch 64-bit PE/COFF support.

The application for IMAGE_FILE_MACHINE_LOONGARCH32 number is 0x6232, and
the application for IMAGE_FILE_MACHINE_LOONGARCH64 number is 0x6264.

Add two base relocation type for LoongArch, named
IMAGE_REL_BASED_LOONGARCH32_MARK_LA and IMAGE_REL_BASED_LOONGARCH64_MARK_LA.

Signed-off-by LI Chao <lichao@loongson.cn>

### CODE REVIEW

**Comment by PRMerger10** [comment]
@kilaterlee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@kilaterlee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kilaterlee** [comment]
Hi @VCZYK ,

The new PR is here, waiting for you review. :)

Thanks.

**Comment by RussKeldorph** [comment]
Superceded by #1067.

/cc @Karl-Bridge-Microsoft @VCZYK

**Pull request closed without merging**
