### PR TITLE
Discussion: unicode API problem with relative path

### PR DESCRIPTION
**Pull request by umairsair**
I worked with CreateFileW API and long paths. When my path is like \\\\?\\C:\temp\longpath\longpath\\..\\..\test then it fails. If I remove ..\\.. then it works.

Is it documentation problem or I need to refer to some other documentation?

### CODE REVIEW

**Comment by PRMerger12** [comment]
@umairsair : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alvinashcraft** [comment]
Hi. Thanks for filing this issue. I will try the scenario and reply with my findings.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-api.html) offer timely answers to a multitude of technical questions surrounding Windows APIs.

A quick question though - Did you have a backslash between the second `longpath` and `..\..`? It seems like there should be another separator there.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. If it's determined that there is a docs issue, we'll come back and make the appropriate changes. Thanks!

**Comment by umairsair** [comment]
> A quick question though - Did you have a backslash between the second longpath and ..\..? It seems like there should be another separator there.

Its lost because of github comment formatting. I have updated first comment, backslash needed to be escaped.

**Pull request closed without merging**
