### PR TITLE
Added missing variable in sample code

### PR DESCRIPTION
**Pull request by msmshazan**
Adding missing variable ps of type PAINTSTRUCT in sample code in Appendix A

### CODE REVIEW

**Comment by PRMerger8** [comment]
@msmshazan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
For the second case, the declaration was already there.

**Comment by stevewhims** [comment]
Thanks, @msmshazan. Safe for you to delete your branch now. :)

**Pull request merged**
