### PR TITLE
Updated wording in wm-input.md

### PR DESCRIPTION
**Pull request by DJm00n**
Minor fix in about-raw-input.md

### CODE REVIEW

**Comment by PRMerger17** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
I'm trying to figure it out how to properly handle  [WM_INPUT](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-input). Could you clarify and fix wording?

>The application must call DefWindowProc so the system can perform cleanup.

vs

>If an application processes this message, it should return zero.

Also there is strange [DefRawInputProc](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-defrawinputproc) exist that is doing nothing(?).
See https://github.com/MicrosoftDocs/sdk-api/pull/178

**Comment by DJm00n** [comment]
@oldnewthing maybe you know the answer?

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
Thanks @DJm00n!

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
