### PR TITLE
maxversiontested update, this should include multiple versions

### PR DESCRIPTION
**Pull request by ChrisGuzak**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ChrisGuzak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ChrisGuzak** [comment]
This addresses https://dev.azure.com/microsoft/OS/_workitems/edit/33687330

**Review by GovM-MSFT — APPROVED** [review]

**Comment by PRMerger15** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mcleanbyron — APPROVED** [review]

**Comment by asklar** [comment]
related: https://github.com/MicrosoftDocs/windows-uwp/pull/3183

**Pull request merged**
