### PR TITLE
Update d3dxmatrixperspectivefovlh.md

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Muzzarino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Pull request merged**
