### PR TITLE
Vertex Shader Stage: Links System Values and Semantics page

### PR DESCRIPTION
**Pull request by alist**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@alist : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, it looks like the CLA hasn't been signed yet (please see comment in the thread above). If you could sign that, then the button will appear on this end for me to complete the PR. Thanks! :)

**Comment by PRMerger7** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alist** [comment]
Done! Sorry about the absolute link :)

**Pull request merged**
