### PR TITLE
Update wm-input-device-change.md

### PR DESCRIPTION
**Pull request by DJm00n**
Add more info. Reformat code.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft hi! Seems tags like `## -parameters` are wrongly rendered on this page after my changes - https://docs.microsoft.com/windows/win32/inputdev/wm-input-device-change
What I did wrong?

**Comment by Karl-Bridge-Microsoft** [comment]
The win32 repo you're working in has a different doc formatting process when building to publish than the sdk-api repo, from which I believe you might've gotten the formatting you inserted. To avoid this in the future, you should emulate the formatting of the docs in the repo you're working in. 

Sorry, I should've caught this. Unfortunately, there are a small number of similar topics in the repo with the same formatting issue. We're scanning and correcting now.

**Pull request merged**
