### PR TITLE
Indicate that the jsproxy.dll APIs are deprecated

### PR DESCRIPTION
**Pull request by Techwolfy**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Techwolfy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Techwolfy** [comment]
The deprecation note should be added to [`InternetDeInitializeAutoProxyDll`](https://docs.microsoft.com/previous-versions/windows/desktop/legacy/aa384580(v=vs.85)) as well, but the legacy documentation doesn't appear to be editable via GitHub.

**Comment by stevewhims** [comment]
I'll take care of https://docs.microsoft.com/previous-versions/windows/desktop/legacy/aa384580(v=vs.85).

**Comment by PRMerger20** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
