### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@taoufrida : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hickeys** [comment]
@taoufrida Thank you for your contribution! I need a little more information before I can approve this PR though. After reviewing your proposed change, I'm not quite clear what your change is intended to address. Can you elaborate a little more on your thinking?

**Review by hickeys — CHANGES_REQUESTED** [review]
see comment

**Comment by hickeys** [comment]
Closing as there has been no activity

**Pull request closed without merging**
