### PR TITLE
Bias range is supposed to be -16..15.99

### PR DESCRIPTION
**Pull request by amarpMSFT**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@amarpMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Hi, @amarpMSFT, and thanks for this pull request. I've reached out internally for confirmation about the range. Do you have any info/spec/whatnot confirming the values?

Thanks!
Steve

**Comment by amarpMSFT** [comment]
This is from the dx specs (d3d11.3 functional spec is one instance), which I wrote, thanks!

(from phone)

________________________________

**Comment by stevewhims** [comment]
Thanks, @amarpMSFT, I found you in the internal GAL and closed the loop. I'll recognize your public username for next time! :) The PR is merged, it's now safe for you to delete your private branch, and thanks again!

-Steve

**Pull request merged**
