### PR TITLE
Add DirectX HDR conceptual content

### PR DESCRIPTION
**Pull request by 13thsymphony**
Replaces the older DXGI HDR/WCG topic with a basic but self-sufficient introduction to HDR and advanced color concepts, API walkthrough, and best practices. This is largely based off of my BUILD 2017 talk but with subsequent API additions.

I am suggesting to add this to the DirectX Articles section since it covers multiple APIs, although the key API surface is primarily DXGI - so it could, for example, be a drop-in replacement for the current DXGI HDR/WCG topic.

I do not have a `ms.assetid` - if this is just any GUID I can generate one.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@13thsymphony : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@13thsymphony : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by zhuman — APPROVED** [review]
This looks great Simon! 😁

**Comment by PRMerger17** [comment]
@13thsymphony : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by 13thsymphony** [comment]
@stevewhims - do we need an asset ID? I can just generate a GUID if that is how they are assigned. Also, there are hyperlinks to D3D11/12/D2D that don't seem to work in the GitHub preview, is there a relative link format I should use?

> * [Direct3D 11](../Direct3D11/atoc-dx-graphics-direct3d-11.md)
> * [Direct3D 12](../Direct3D12/direct3d-12-graphics.md)
> * [Direct2D](../Direct2D/direct2d-portal.md)

**Comment by stevewhims** [comment]
We don't need an asset id, those are only for topics that were ever published at an old (obsolete) msdn url. For links, use only the part of the target URL that comes after the locale code, including the leading slash. This makes the link functional both online and in offline books. For example, if the url in the brower's address bar is `https://docs.microsoft.com/en-us/windows/win32/direct3d12/direct3d-12-graphics`, then the link syntax is `/windows/win32/direct3d12/direct3d-12-graphics`. Note that you don't include the `.md` of the filename when you use this link syntax.

**Comment by PRMerger14** [comment]
@13thsymphony : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by 13thsymphony** [comment]
Thanks! Looks like all the required reviewers have signed off.

**Comment by 13thsymphony** [comment]
(Mistakenly closed). @stevewhims let's not block on Chas. What are next steps on this PR? I don't have write access to the repo.

**Comment by stevewhims** [comment]
Sounds like you're ready to merge, so I went ahead and did that. I'll monitor the live site and make sure it goes live.

**Pull request merged**
