### PR TITLE
Update using-the-checkv4-exe-utility-2.md

### PR DESCRIPTION
**Pull request by kmustang**
Added a comment that this utility was removed from the SDK in v8.0.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@kmustang : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Thanks, @kmustang! :)

**Comment by stevewhims** [comment]
FYI, I'm currently working on a subsequent PR that changes the timeline back to how you had it: specifically, that the utility is NOT in the Win8 SDK. That should be live soon.

**Comment by kmustang** [comment]
Thanks!

On Oct 17, 2019, at 2:05 PM, Steven White <notifications@github.com> wrote:

FYI, I'm currently working on a subsequent PR that changes the timeline back to how you had it: specifically, that the utility is NOT in the Win8 SDK. That should be live soon.

**Pull request merged**
