### PR TITLE
[BLOCKED ON CLA] Update your-first-windows-program.md

### PR DESCRIPTION
**Pull request by JoshuaLnt**
changes made:
-   const TCHAR CLASS_NAME[] = _T("Sample Window Class");
-   literal "Strings" converted to _T("Strings")
-> TCHAR and the _T macro ensure that string literals are treated appropriately based on the build configuration and are used to handle both ANSI and Unicode builds.

### CODE REVIEW

**Comment by stevewhims** [comment]
Hi, @JoshuaLnt, could you accept the CLA please? Details in the comment above.

Thanks!
-Steve

**Comment by JoshuaLnt** [comment]
@microsoft-github-policy-service agree [company="default"]

**Comment by JoshuaLnt** [comment]
@microsoft-github-policy-service agree

**Comment by JoshuaLnt** [comment]
This was accidentally closed. I meant to delete another repo. 
If this needs to be reopened, either copy the changes or email me.

**Pull request closed without merging**
