### PR TITLE
Update enumerating-providers.md

### PR DESCRIPTION
**Pull request by JayGuan**
Update StringFromCLSID to StringFromGUID2
Clean up white spaces

### CODE REVIEW

**Comment by PRMerger15** [comment]
@JayGuan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @JayGuan - according to https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-stringfromclsid#remarks, StringFromCLSID calls the StringFromGUID2 function.

**Comment by idigdoug** [comment]
> Hi @JayGuan - according to https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-stringfromclsid#remarks, StringFromCLSID calls the StringFromGUID2 function.

StringFromCLSID allocates a string, copies the StringFromGUID2 into the new allocation, and returns it. The caller needs to free the allocation.

StringFromGUID2 uses existing memory, which is more efficient, and is simpler for C/C++ callers.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the info, @idigdoug.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
