### PR TITLE
Locations are Win 10 and Win 11 relevant

### PR DESCRIPTION
**Pull request by RDMacLachlan**
Updating the pathing to the Win 10 / 11 specific Win App SDK for the makeappx.exe

### CODE REVIEW

**Comment by PRMerger3** [comment]
@RDMacLachlan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by drewbatgit — APPROVED** [review]

**Comment by drewbatgit** [comment]
#sign-off

**Comment by KalleOlaviNiemitalo** [comment]
This change would lose the information that, makeappx.exe is installed to both x86 and x64 directories on x64 OS.

**Comment by PRMerger7** [comment]
@RDMacLachlan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RDMacLachlan** [comment]
@KalleOlaviNiemitalo - I've added extra bullet points to the document to include the x64 paths to the makeappx.exe tool on 64-bit operating systems. Hope that this will resolve your concerns.

**Review by drewbatgit — APPROVED** [review]

**Comment by drewbatgit** [comment]
#sign-off

**Pull request merged**
