### PR TITLE
Revert "adding a note"

### PR DESCRIPTION
**Pull request by JYOTHIRMAISURI**
@stevewhims

Thanks for the review. This note (#PR 610) was waiting final confirmation for publishing, hence, did not sign-off. I will sign-off this once I receive a confirmation. Until then, please do not merge / make it live. I should be able to sign-off this in a day or two. Thanks.

Please revert these merges for now.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@JYOTHIRMAISURI : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JYOTHIRMAISURI** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@JYOTHIRMAISURI: I'm sorry - only the author of this article, @stevewhims, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by JYOTHIRMAISURI** [comment]
@stevewhims  thank much for the quick revert merge.

**Pull request merged**
