### PR TITLE
Create Regarding-DPAPI-Backup-Keys-on-Active-Directory-Domain-Control…

### PR DESCRIPTION
**Pull request by ryanriesMSFT**
…lers.md

Customer-requested documentation. Contact jories for more information.

### CODE REVIEW

**Comment by alvinashcraft** [comment]
Hi @ryanriesMSFT. Thanks for submitting this PR. Where do you see this page being added in the documentation. Would it be nested under "About CNG"-->"CNG DPAPI" where this page is located? https://learn.microsoft.com/windows/win32/seccng/cng-dpapi

I can add the table of contents info, add the required metadata to the header of this new file, and review the content to help get this information added to the docs.

**Comment by ryanriesMSFT** [comment]
Yes, thank you, that would be perfect.
________________________________

**Comment by ryanriesMSFT** [comment]
@alvinashcraft So who are we waiting on to get this PR merged?

**Comment by alvinashcraft** [comment]
Hi @ryanriesMSFT. Apologies for the delay. This month has been full of documentation deliverables tied to MS Build. I created a work item to get this wrapped up in early June (early next week). I will be creating another PR because there isn't an easy way for me to add more files to your existing PR on the public repo. I'll add you as a reviewer when it's ready.

**Comment by alvinashcraft** [comment]
Closing this since we got it merged through the internal repo. Thanks for submitting this!

**Pull request closed without merging**
