### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by DJm00n**
`/previous-versions/windows/desktop/legacy/ms644981(v=vs.85)` -> `/windows/win32/winmsg/getmsgproc`
`/previous-versions/windows/desktop/legacy/ms644982(v=vs.85)` -> `/windows/win32/winmsg/journalplaybackproc`
`/previous-versions/windows/desktop/legacy/ms644983(v=vs.85)` -> `/windows/win32/winmsg/journalrecordproc`
`/previous-versions/windows/desktop/legacy/ms644984(v=vs.85)` -> `/windows/win32/winmsg/keyboardproc`
`/previous-versions/windows/desktop/legacy/ms644985(v=vs.85)` -> `/windows/win32/winmsg/lowlevelkeyboardproc`
`/previous-versions/windows/desktop/legacy/ms644986(v=vs.85)` -> `/windows/win32/winmsg/lowlevelmouseproc`
`/previous-versions/windows/desktop/legacy/ms644987(v=vs.85)` -> `/windows/win32/winmsg/messageproc`
`/previous-versions/windows/desktop/legacy/ms644988(v=vs.85)` -> `/windows/win32/winmsg/mouseproc`
`/previous-versions/windows/desktop/legacy/ms644991(v=vs.85)` -> `/windows/win32/winmsg/shellproc`
`/previous-versions/windows/desktop/legacy/ms644992(v=vs.85)` -> `/windows/win32/winmsg/sysmsgproc`
`/previous-versions/windows/desktop/legacy/ms633573(v=vs.85)` -> `/windows/win32/api/winuser/nc-winuser-wndproc`

### CODE REVIEW

**Comment by DJm00n** [comment]
Still missing actual docs for:

https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644978(v=vs.85) DebugProc
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644980(v=vs.85) ForegroundIdleProc
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644977(v=vs.85) CBTProc
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644975(v=vs.85) CallWndProc

**Review by hickeys — APPROVED** [review]

**Comment by hickeys** [comment]
#sign-off

**Comment by stevewhims** [comment]
Recommend taking the transformations described in the Description (which is great), and applying them in a writer's own PR. That'll be quicker than eyeballing for correctness every change in the 150 affected files. :)

**Comment by stevewhims** [comment]
[like]  Steve White reacted to your message:
________________________________

**Pull request merged**
