### PR TITLE
Update wavereadlaneat.md

### PR DESCRIPTION
**Pull request by briannagerads**
updating MSDN to match github docs

### CODE REVIEW

**Comment by PRMerger10** [comment]
@briannagerads : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@briannagerads : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
FYI, my SME contact has confirmed that this change is technically correct, I'll be happy to complete it when you're ready.

**Comment by AdamJMiles** [comment]
@stevewhims I believe Bri has left Microsoft. Can this PR be completed?

**Comment by stevewhims** [comment]
> @stevewhims I believe Bri has left Microsoft. Can this PR be completed?

I don't have the usual affordance by which I can complete the PR. In its place it says "This pull request is still a work in progress". 

Nor do I see a way to change the PR's state from draft to non-draft. Do you see any way of doing that on your end?

**Comment by stevewhims** [comment]
> @stevewhims I believe Bri has left Microsoft. Can this PR be completed?

On second thoughts, it's easier if I just re-do the change in my own PR. https://github.com/MicrosoftDocs/win32-pr/pull/1099.

So I'll close this. Thank you!

**Pull request closed without merging**
