### PR TITLE
Update about-keyboard-input.md

### PR DESCRIPTION
**Pull request by DJm00n**
Add more links.
Fix example code (BYTE scanCode -> WORD scanCode).
Clarify info on WM_CHAR encoding a bit.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DJm00n - "deprecated" might be too strong. Both KF_DLGMODE and KF_MENUMODE are still in the winuser source. If in source, must be documented.

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft `WM_KEYDOWN` etc. `lParam` description said that these bits are `Reserved; do not use.`. I haven't found any additional info on them.

Anyways I brought these two back.

**Comment by PRMerger20** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
