### PR TITLE
Update name-space.md

### PR DESCRIPTION
**Pull request by ghane**
Small language changes, and expanded/defined "FQDN"

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ghane : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, @ghane, if you could go ahead and sign the CLA (see the link in the comment above), then I'll be able to complete this pull-request.

Thanks!
Steve

**Comment by stevewhims** [comment]
Hi, @ghane, just a reminder that we're blocked on completing this PR at the moment. Do you mind going ahead and signing the CLA (see the link in the comment above)?

Thanks!
Steve

**Comment by PRMerger12** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghane** [comment]
> Hi, @ghane, just a reminder that we're blocked on completing this PR at the moment. Do you mind going ahead and signing the CLA (see the link in the comment above)?

Apologies, I missed this in my Inbox.  Done now.

**Pull request merged**
