### PR TITLE
Update porting-from-direct3d-11-to-direct3d-12.md

### PR DESCRIPTION
**Pull request by rpavlik**
Fix typo.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@rpavlik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@rpavlik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rpavlik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@rpavlik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Thank you!

**Pull request merged**
