### PR TITLE
Update information on HDR and WCG content capture

### PR DESCRIPTION
**Pull request by imbushuo**
A lot of developers don't know how to implement this (do you ever see screenshot tools support HDR/WCG on Windows?) and and they need proper resources to achieve image capture on WCG/HDR platforms.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@imbushuo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by imbushuo** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@imbushuo: I'm sorry - only the author of this article, @stevewhims, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by stevewhims — APPROVED** [review]
Thank you!

**Pull request merged**
