### PR TITLE
Update create-a-simple-combo-box.md

### PR DESCRIPTION
**Pull request by RussKie**
Fix formatting

### CODE REVIEW

**Comment by PRMerger12** [comment]
@RussKie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@RussKie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@RussKie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
@RussKie, thanks for submitting these fixes.

**Pull request merged**
