### PR TITLE
extra fileds and column type change

### PR DESCRIPTION
**Pull request by shubell**
Added extra fields:
	Event_Source,
	Framed_MTU,
	MS_RAS_Correlation_ID,
	MS_Network_Access_Server_Type,
	SAM_Account_Name,
	Fully_Qualifed_User_Name
Increased the size of columns octets and packets. Sometimes int is too small.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@shubell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@shubell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by shubell — COMMENTED** [review]
typo , not .

**Comment by MatchaMatch** [comment]
Thanks for your contribution.  I've merged your changes and they should be live soon.

**Pull request merged**
