### PR TITLE
Need confirmation on below points

### PR DESCRIPTION
**Pull request by KrupalJoshi**
Please correct my understanding regarding execute WMI query on local computer. Understanding based on below documents. And please make changes in documents if those are correct.

https://docs.microsoft.com/en-us/windows/win32/wmisdk/connecting-to-wmi-on-a-remote-computer
https://docs.microsoft.com/en-us/windows/win32/wmisdk/setting-the-security-on-iwbemservices-and-other-proxies

Below points are not permitted to connecting WMI to local computer or executing query on local computer.
1. We can't provide user credentials to "ConnectServer" API.
2. We can't provide user credentials or authentication information (domain, username, password) on WMI query/proxy. Something like using "CoSetProxyBlanket" API or "CoInitializeSecurity" API.

Summary: Is there any way to provide user credentials to execute WMI query?

### CODE REVIEW

**Comment by PRMerger18** [comment]
@KrupalJoshi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Hi, @KrupalJoshi. In general, a pull-request (PR) is the right workflow only when we're certain exactly what change to make to the content. In this case, though, you have a question about the product, specifically: "Summary: Is there any way to provide user credentials to execute WMI query?"

It seems like we're not ready yet to make changes to the content.

So, I would recommend that you pursue this as a question about the product. If you visit a relevant topic, and click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Sorry that I couldn't be of more immediate help here. I'll go ahead and close the PR now.

-Steve

**Comment by KrupalJoshi** [comment]
Thanks @stevewhims . 
Before this i have open an issue in github but unfortunately i didn't found correct repository for this.

https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/issues/271

**Comment by stevewhims** [comment]
Hi, @KrupalJoshi. It looks like updates to the docs are going to be taken care of as a result of that GitHub Issue (the one you link to above, #271). I don't think that there's anything else for you to do here, but please let me know if I'm misinterpreting anything.

~Steve

**Comment by KrupalJoshi** [comment]
@stevewhims Yes, probably it will be change in document only. But not getting clear idea for my query :)

**Comment by stevewhims** [comment]
I see, well it looks like you're doing the right thing, and continuing the conversation on that GitHub issue (#271). And, if necessary, you can always re-open a closed GitHub issue that you created.

Alternatively, you could start a new thread. If you have feedback about a particular API topic (that is, you believe that the content is incorrect, or that info needed to succeed with a common scenario is missing), then you can visit that topic and click **Send feedback about** \> **This page**.

For other questions/feedback about the product, you can click **Send feedback about** \> **This product**, and you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

-Steve

**Pull request closed without merging**
