### PR TITLE
Remove content about Shell Extensions Approved registry key

### PR DESCRIPTION
**Pull request by ChrisGuzak**
this functionality was removed prior to Windows 7.

### CODE REVIEW

**Comment by luedersj** [comment]
> this functionality was removed prior to Windows 7.

Instead of just deleting should we note that this is no longer required as of Win7?

**Review by RobertStPierre — APPROVED** [review]
Thanks for updating this Chris!

**Comment by ChrisGuzak** [comment]
> > this functionality was removed prior to Windows 7.
> 
> Instead of just deleting should we note that this is no longer required as of Win7?

I don't think so. it really never worked so no reason to document it at all.

**Comment by ChrisGuzak** [comment]
@jwmsft can you complete this?

**Pull request merged**
