### PR TITLE
Update isolated-user-mode--ium--processes.md

### PR DESCRIPTION
**Pull request by turingcompl33t**
Edit the implications section to specify the APIs of interest:
- CreateRemoteThread rather than CreateThread 
- VirtualAllocEx rather than VirtualAlloc

to account for the fact that the section in question is addressing targeting other processes via these APIs, which the functions as written  lack the ability to do.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@turingcompl33t : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@turingcompl33t : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
