### PR TITLE
Fix article "Retrieving Counter Names and Help Text"

### PR DESCRIPTION
**Pull request by ratijas**
- Rename file to match article's title 
 - Fix XML entities
 - Elaborate on language identifier format and fix the example
 - Fix example accordingly
 - Document a bug about localized `Help <langid>` always returning strings in English

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ratijas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ratijas** [comment]
I've done my research and homework, all code of experiments are  uploaded here, in case anyone want to verify my statements: https://github.com/ratijas/windows-rust-counters

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @ratijas!

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by ratijas** [comment]
Thanks for such a fast merge! Impressive. Though, I see, I should really work harder on my grammar.

About that `Help <langid>`... I think it should be reported as a bug elsewhere, bug I'm not sure where exactly.

**Comment by Karl-Bridge-Microsoft** [comment]
These might help:

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Pull request merged**
