### PR TITLE
Break up numbered list into multiple lines

### PR DESCRIPTION
**Pull request by DavidLyhedDanielsson**
It is clearer that it is a list and is easier to follow.

~~Using only "1." makes sure the list isn't broken if items are added/removed.~~

### CODE REVIEW

**Comment by stevewhims** [comment]
Yes, I like the technique of using `1.` for all list items. But only when the topic doesn't refer to list items by number. Here the list itself refers to items by number. In those cases I prefer to be explicit so that if anyone changes the number of items, or their sequence, there's more chance that they'll fix up the references. I removed some redundant whitespace, though.

Thanks!
-Steve

**Comment by stevewhims** [comment]
Hi, it looks like the CLA hasn't been signed yet (please see comment in the thread above). If you could sign that, then the button will appear on this end for me to complete the PR. Thanks! :)

**Comment by DavidLyhedDanielsson** [comment]
@microsoft-github-policy-service agree

**Comment by DavidLyhedDanielsson** [comment]
> Yes, I like the technique of using `1.` for all list items. But only when the topic doesn't refer to list items by number. Here the list itself refers to items by number. In those cases I prefer to be explicit so that if anyone changes the number of items, or their sequence, there's more chance that they'll fix up the references.

I agree. Looks good to me!

**Review by stevewhims — APPROVED** [review]

**Pull request merged**
