### PR TITLE
Update complete-server-code.md  --- fixed comment

### PR DESCRIPTION
**Pull request by pea-sys**
Create a SOCKET for connecting to server → Create a SOCKET for the server to listen for client connections

### CODE REVIEW

**Comment by PRMerger19** [comment]
@pea-sys : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Hi, it looks like the CLA hasn't been signed yet (please see comment in the thread above). If you could sign that, then the button will appear on this end for me to complete the PR. Thanks! :)

**Review by stevewhims — COMMENTED** [review]
For the wording in the first file, I'll go ahead and make that change in another PR, thank you! :)

For the changes in the second file, there are so many occurrences of things like escaped underscores, and HTML tables, that it doesn't scale if we have customers fix them manually one by one, and then have writers double-check every change on by one. Across the docs it's likely there'd be hundreds of thousands, or millions, of such edits. Lining up markdown tables like that isn't necessary, either (I generally remove all doubled spaces and all doubled hyphens). And we don't want to perpetuate the use of HTML in markdown files by adding CSS styling; we should where possible be replacing HTML with markdown. I think that all changes of this sort are best done in an automated fashion by the writing team.

**Comment by stevewhims** [comment]
I've taken the change to the first file and I've used it in a separate PR. That change is live now. But I'll go ahead and close this PR without taking the changes to the second file (for the reasons described above).

Thanks!
-Steve

**Comment by PRMerger-2** [comment]
@pea-sys : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by pea-sys** [comment]
＠[stevewhims](https://github.com/stevewhims)
Thank you for your review

**Pull request closed without merging**
