### PR TITLE
Clipboard: Fix errors regarding how to respond to WM_RENDERALLFORMATS

### PR DESCRIPTION
**Pull request by metathinker**
This change corrects a few errors in how to respond to the [`WM_RENDERALLFORMATS` window message](https://docs.microsoft.com/en-us/windows/win32/dataxchg/wm-renderallformats), which is posted by Windows to a window that is the "clipboard owner" (the creator of the data currently on the clipboard) when that window is being destroyed.

- If you want to render some clipboard formats in response to WM_RENDERALLFORMATS, you must first call OpenClipboard(). I fixed an incorrect statement that you must _not_ call OpenClipboard().

- After calling OpenClipboard(), you should call GetClipboardOwner() to check that your window is still the clipboard owner, since another app may have opened and taken ownership of the clipboard by calling OpenClipboard() and EmptyClipboard() before you opened the clipboard, and you don't want to overwrite that other app's data. I added a note of that to the docs.

- You should _not_ normally call EmptyClipboard() yourself before rendering data and setting it with SetClipboardData(), since that will erase the formats you have already rendered. I removed the incorrect claim that you _must_ call EmptyClipboard(), and replaced it with a warning not to do so in most cases.

I also updated some URL links that still work but redirect, and fixed a grammatical typo.

Pairs with https://github.com/MicrosoftDocs/sdk-api/pull/305

### CODE REVIEW

**Comment by PRMerger14** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by metathinker** [comment]
I actually happened to notice these mistakes when researching an otherwise unrelated topic - I saw that way back in December 2012, @oldnewthing had actually [pointed out the mistakes](https://devblogs.microsoft.com/oldnewthing/20121224-00/?p=5763) in response to a confused reader, and I was surprised to find out that 7.5 years later, they were still not yet corrected.

**Comment by PRMerger10** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by metathinker** [comment]
Even Charles Petzold's _Programming Windows_ gets this wrong, interestingly enough. The section on clipboard delayed rendering in my copy of the 5th edition (pages 583-584, or [here in the O'Reilly subscription ebook](https://learning.oreilly.com/library/view/programming-windows-fifth/9780735642225/ch12s02.html)) says that when handling WM_RENDERALLFORMATS, you "should" empty the clipboard with EmptyClipboard(), while in fact it is not necessary to do so and, as I described above, you almost certainly should not do so since you'll destroy all the data formats you already rendered.

Petzold's code snippet also fails to do the GetClipboardOwner() check after calling OpenClipboard(). But that's not as big of a bug, since the race to obtain the OpenClipboard() clipboard lock will almost always be won by the window that received WM_RENDERALLFORMATS.

**Comment by PRMerger8** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MatchaMatch** [comment]
Thanks for your (extensive) contribution! I've merged your changes and they should be live soon.

**Pull request merged**
