### PR TITLE
fixed Resource Binding Flow of Control link

### PR DESCRIPTION
**Pull request by badasahog**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@badasahog : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by badasahog** [comment]
the first sentence is a mess but I don't know what to change it to. 
"The key to resource binding in DirectX 12 are the concepts of a descriptor, descriptor tables, descriptor heaps, and a root signature."

the key to understanding resource binding? the key to binding a resource? why is descriptor singular but descriptor tables is not?

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, @badasahog, if you could sign the CLA (see comment above), then I'll be able to ahead and complete this PR.

Thanks!
Steve

**Comment by PRMerger16** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
