### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Tarluna**
There was a type where you would read fro instead of for

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Tarluna : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Youssef1313** [comment]
There are two other occurrences of the same typo:
https://github.com/MicrosoftDocs/win32/search?q=fro&unscoped_q=fro

**Comment by hickeys** [comment]
@Youssef1313 Thanks for the heads up. I'll address these in a separate PR

**Review by hickeys — APPROVED** [review]
Good catch, thank you.

**Comment by hickeys** [comment]
#sign-off

**Pull request merged**
