### PR TITLE
Remove frquery.h from HLSL vector doc

### PR DESCRIPTION
**Pull request by pow2clk**
No idea why this was here. It has nothing to do with HLSL

### CODE REVIEW

**Comment by PRMerger8** [comment]
@pow2clk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — CHANGES_REQUESTED** [review]
We don't want to remove metadata, nor the Requirements block. Where the wrong header file is being cited, we should correct that to the right one.

**Comment by pow2clk** [comment]
There is no header, it's an HLSL intrinsic. It's available when using the HLSL compiler without any header.

**Review by stevewhims — APPROVED** [review]
I see; it's a conceptual topic, so removing these metadata fields is ok, Approved!

**Comment by PRMerger14** [comment]
@pow2clk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
