### PR TITLE
Add known config problem when trying to collect user mode dumps

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@andreiztm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by andreiztm** [comment]
Thanks for the quick action.

**Pull request merged**
