### PR TITLE
Update wchar-t.md

### PR DESCRIPTION
**Pull request by benjymous**
Fixed some mangled characters

### CODE REVIEW

**Comment by PRMerger17** [comment]
@benjymous : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by elisee** [comment]
According to [this page](https://www.i18nqa.com/debug/utf8-debug.html), the `â€“` mangled characters should map to `–` rather than a space.

**Comment by benjymous** [comment]
Credit to @fasterthanlime for spotting

https://twitter.com/fasterthanlime/status/1248695725313187847

**Review by mcleanbyron — APPROVED** [review]

**Comment by benjymous** [comment]
> According to [this page](https://www.i18nqa.com/debug/utf8-debug.html), the `â€“` mangled characters should map to `–` rather than a space.

I thought that too, but the hyphen didn't seem to make much sense grammatically

**Pull request merged**
