### PR TITLE
fix broken link

### LINKED ISSUE #1934: Broken link in DX12 doc
**Describe the bug**
https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles
On this page, the link to D3D12_COMMAND_LIST_TYPE in the top outline goes to https://docs.microsoft.com/en-us/windows/ instead of someplace within the document.

**To Reproduce**
Open link - https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles
Click on link D3D12_COMMAND_LIST_TYPE
Notice you are not on a page related to D3D12_COMMAND_LIST_TYPE.

**Expected behavior**
Jump to information about D3D12_COMMAND_LIST_TYPE

**Desktop (please complete the following information):**
Win10, Chrome browser

### PR DESCRIPTION
**Pull request by mairaw**
Fixes https://github.com/MicrosoftDocs/feedback/issues/1934

### CODE REVIEW

**Comment by PRMerger6** [comment]
@mairaw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Maira, if you don't have the Merge UI, then I'll merge it.

**Comment by mairaw** [comment]
I don't have it. Please do!

**Comment by stevewhims** [comment]
There you go. Safe to delete your working branch now.

**Pull request merged**
